server:
  port: 8081

spring:
  datasource:
    name: microService1
    url: jdbc:mariadb://localhost:3306/microService1
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#

